// <auto-generated />
using System;
using ASP_Contact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_Contact.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ASP_Contact.Models.ContactEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Created = new DateTime(2024, 11, 6, 20, 30, 5, 865, DateTimeKind.Local).AddTicks(6971),
                            Priority = 1,
                            dateOfBirth = new DateTime(2000, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "adam@wsei.edu.pl",
                            name = "Andzej",
                            phone = "127813268163",
                            surname = "Kowalskiiii"
                        },
                        new
                        {
                            id = 2,
                            Created = new DateTime(2024, 11, 6, 20, 30, 5, 865, DateTimeKind.Local).AddTicks(7030),
                            Priority = 3,
                            dateOfBirth = new DateTime(1999, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "ewa@wsei.edu.pl",
                            name = "Ewa",
                            phone = "293443823478",
                            surname = "Nowak"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
